### ISSUE TITLE
Installation Error on CentOS #29

### ISSUE THREAD

**Issue by genomaths** [stevengj/cubature#12]
When trying the installation of 'cubature' R package in CentOS, which is a R package to use your C++ library "cubature" in R, I got the following report:

In file included from ./src/divonne/common.c:14:0,
from ./src/common/CSample.c:77,
from ./src/divonne/Divonne.c:14:
./src/divonne/Split.c: In function ‘SolveEqs’:
./src/divonne/Split.c:119:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
for(int first_time = 1 ; c >= cut; --c) {
^
./src/divonne/Split.c:119:3: note: use option -std=c99 or -std=gnu99 to compile your code
make[1]: *** [libcuba.a(Divonne.o)] Error 1
make[1]: Leaving directory `/tmp/RtmpzyLsw8/R.INSTALLec444ba5a993/cubature/src/Cuba-4.2'
make: *** [cuba.ts] Error 2
ERROR: compilation failed for package ‘cubature’

There is not problem at all on Linux OS.

Would you please help me with this issue?
Best,
Robersy

**Comment by stevengj** [comment]
That error message is not in the cubature code, it's in `src/divonne/Split.c` which is not part of this package.

The cubature package itself compiles with C89 or C99.
