### ISSUE TITLE
Open question

### ISSUE THREAD

**Issue by Pulpas** [stevengj/cubature#19]
I would like to thank you for your very interesting work, I am not very familiar with the mathematical derivations, but I am very keen to incorporate your software in my day-to-day research work. To do so, I would have a very simple question:

Is it possible to use this library to compute the volume and surface moments of any convex shape ?

**Comment by stevengj** [comment]
Yes.

That being said, you have to know enough math to formulate your problem in terms of integrals over hypercubes, which probably involves some changes of variables for integrating weird shapes.  It also depends on how you parameterize those shapes (e.g. by surface triangulations?).  But github issues are not a forum for calculus tutorials.

**Comment by Pulpas** [comment]
The "Yes" was more than enough, thanks.
