### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by fredRos** [stevengj/cubature#3]
I wanted to include the hcubature code in another GPL project. Then I noticed that the `COPYING` file says the project is under GPL v3. But inside `hcubature.c` it states GPL v2. Now which is the right version of the license? I know this is a boring detail but you can presumably clear this up easily.

**Comment by stevengj** [comment]
As stated in the copyright notice, it is GPL "v2 or later" — i.e. you can use v2 or any later version released by the FSF, at your option.
