### ISSUE TITLE
Can it be estimated how many integrand evaluations will be needed?

### ISSUE THREAD

**Issue by pedrohnv** [stevengj/cubature#5]
Hi,
I am to integrate a complex function in one variable f : R -> C. I wonder if I can estimate theoretical how many evaluations will be needed to do it based on the absolute and relative errors (using h-cubature).

I did a quick look at _J. Berntsen, T. O. Espelid, and A. Genz, “An adaptive algorithm for the approximate calculation of multiple integrals,” ACM Trans. Math. Soft. 17 (4), 437–451 (1991)._, and I've seen some experimental results, but no theoretical one.

**Comment by stevengj** [comment]
No, it depends a lot on the specific function being integrated, not just on the errors.

To pick an extreme example, a constant function will give zero error immediately (i.e. with the minimal number of function evaluations), whereas a highly oscillatory function like `1 + sin(100x²)` will require a lot more evaluations even to get a few digits.
