### ISSUE TITLE
hcubature hanging and leaking memory on a simple multivariate normal expectation calculation

### ISSUE THREAD

**Issue by bnaras** [stevengj/cubature#7]
I got a bug report on my R package from a user and found that hcubature is having trouble with a simple integral of x * f(x) where f is 2-d multivariate normal density.  

I provide a reproducible example on [my repo](https://github.com/bnaras/hcubature_problem)

I checked that the problem occurs both on Unix and Mac. Pcubature works nicely though!

**Comment by stevengj** [comment]
~~Does HCubature.jl work?~~ Sorry, wrong language!  Might be the same problem as was fixed in https://github.com/stevengj/HCubature.jl/pull/5 though.  Would be nice to apply the same fix to the C cubature routine.
